### PR TITLE
tidies and fixes hiding version while presenting

### PR DESCRIPTION
**Pull request by kzidane**
* info is now a Plugin not a Dialog
* removes hiding version pref
* fixes hiding version number while presenting after reload
* forcibly hides version number while presenting
* removes CSS and templates as no longer needed

### CODE REVIEW

**Comment by dmalan** [comment]
Try now!

**Comment by dmalan** [comment]
And definitely tested? Lots of changes!

**Comment by kzidane** [comment]
Thanks!

**Comment by kzidane** [comment]
@dmalan, yup.
✓No errors
✓phpMyAdmin and  Web server items work as expected
✓ Version number is toggled as expected

**Comment by dmalan** [comment]
Thanks!

**Pull request merged**
